#!/bin/sh

echo "Checking for an older version of AutoBouquets E2 in the system..."

if [ -d /usr/lib/enigma2/python/Plugins/Extensions/AutoBouquets ]; then
	rm -rf /usr/lib/enigma2/python/Plugins/Extensions/AutoBouquets > /dev/null 2>&1
	echo "An older version of AutoBouquets E2 was found and removed"
	echo "Proceeding to installation..."
else
	echo "AutoBouquets E2 was not found in the system"
	echo "Proceeding to installation..."
fi

exit 0

